[package]
name = "octs"
description = "Good byte manipulation library"

version = "0.1.0"
edition = "2021"

[lints.rust]
# missing_docs = "warn"
unused_crate_dependencies = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[features]
default = ["std"]

std = ["bytes/std"]

i128 = []

[dependencies]
bytes = { version = "1.6.0", default-features = false }
